### ISSUE TITLE
about paper

### ISSUE THREAD

**Issue by zjn0613** [exceefind/FeatWalk#1]
Can you share the paper？
Thanks very mach！

**Comment by exceefind** [comment]
Hello, thank you for your interest! Since the paper has not been uploaded to the arXiv, I am unable to provide you with a link to the paper at this time. You can wait and follow the progress of paper publications at AAAI 2024, and I believe you will be able to see the paper soon.

**Comment by zjn0613** [comment]
The paper has been published. Thanks for your reply！
